# Generated by Django 4.0.6 on 2022-07-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={'verbose_name': 'Our Snack', 'verbose_name_plural': 'Our Snacks'},
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(default='Snack', help_text='Snack Name', max_length=64),
        ),
    ]
